# https://wiki.hyprland.org/Configuring/Monitors/

monitor = $monitor_main, 2560x1440@144hz, 0x0,      1
monitor = $monitor_side, 1920x1080@75hz,  2560x289, 1, transform, 1
# hyprlang if MIRROR_TO_TV
	monitor = $monitor_tv,   3840x2160@60hz,  3640x400, 2.5, mirror, $monitor_main
# hyprlang endif
# hyprlang if !MIRROR_TO_TV
	monitor = $monitor_tv,   3840x2160@60hz,  3640x400, 2.5
# hyprlang endif
monitor = ,              preferred,       auto,     1
